name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with: 
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with: 
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Lint JS
        run: npm run lint:js -- --max-warnings 0
      - name: Lint CSS
        run: npm run lint:css -- --max-warnings 0